name:                bitcoin
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/setrar/bitcoin#readme
license:             BSD3
author:              Setra R
maintainer:          setrar@valiha.com
copyright:           setrar
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - lens-aeson
  - bytestring
  - text
  - http-conduit

executables:
  bitcoin:
    source-dirs:      src
    main:             Main.hs
